# ReadTheDocs configuration for UDProbe
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - python -m pip install --upgrade pip
    - pip install -r docs/requirements.txt
    - mkdocs build

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
