// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: llama.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Probe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Tos           []byte                 `protobuf:"bytes,2,opt,name=tos,proto3" json:"tos,omitempty"`
	Sent          uint64                 `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	Rcvd          uint64                 `protobuf:"varint,4,opt,name=rcvd,proto3" json:"rcvd,omitempty"`
	Rtt           uint64                 `protobuf:"varint,5,opt,name=rtt,proto3" json:"rtt,omitempty"`
	Lost          bool                   `protobuf:"varint,6,opt,name=lost,proto3" json:"lost,omitempty"`
	Padding       []byte                 `protobuf:"bytes,7,opt,name=padding,proto3" json:"padding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Probe) Reset() {
	*x = Probe{}
	mi := &file_llama_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Probe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Probe) ProtoMessage() {}

func (x *Probe) ProtoReflect() protoreflect.Message {
	mi := &file_llama_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Probe.ProtoReflect.Descriptor instead.
func (*Probe) Descriptor() ([]byte, []int) {
	return file_llama_proto_rawDescGZIP(), []int{0}
}

func (x *Probe) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Probe) GetTos() []byte {
	if x != nil {
		return x.Tos
	}
	return nil
}

func (x *Probe) GetSent() uint64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *Probe) GetRcvd() uint64 {
	if x != nil {
		return x.Rcvd
	}
	return 0
}

func (x *Probe) GetRtt() uint64 {
	if x != nil {
		return x.Rtt
	}
	return 0
}

func (x *Probe) GetLost() bool {
	if x != nil {
		return x.Lost
	}
	return false
}

func (x *Probe) GetPadding() []byte {
	if x != nil {
		return x.Padding
	}
	return nil
}

var File_llama_proto protoreflect.FileDescriptor

const file_llama_proto_rawDesc = "" +
	"\n" +
	"\vllama.proto\x12\x05proto\"\x9f\x01\n" +
	"\x05Probe\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x10\n" +
	"\x03tos\x18\x02 \x01(\fR\x03tos\x12\x12\n" +
	"\x04sent\x18\x03 \x01(\x04R\x04sent\x12\x12\n" +
	"\x04rcvd\x18\x04 \x01(\x04R\x04rcvd\x12\x10\n" +
	"\x03rtt\x18\x05 \x01(\x04R\x03rtt\x12\x12\n" +
	"\x04lost\x18\x06 \x01(\bR\x04lost\x12\x18\n" +
	"\apadding\x18\a \x01(\fR\apaddingB Z\x1egithub.com/nsw3550/llama/protob\x06proto3"

var (
	file_llama_proto_rawDescOnce sync.Once
	file_llama_proto_rawDescData []byte
)

func file_llama_proto_rawDescGZIP() []byte {
	file_llama_proto_rawDescOnce.Do(func() {
		file_llama_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llama_proto_rawDesc), len(file_llama_proto_rawDesc)))
	})
	return file_llama_proto_rawDescData
}

var file_llama_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_llama_proto_goTypes = []any{
	(*Probe)(nil), // 0: proto.Probe
}
var file_llama_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llama_proto_init() }
func file_llama_proto_init() {
	if File_llama_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llama_proto_rawDesc), len(file_llama_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_llama_proto_goTypes,
		DependencyIndexes: file_llama_proto_depIdxs,
		MessageInfos:      file_llama_proto_msgTypes,
	}.Build()
	File_llama_proto = out.File
	file_llama_proto_goTypes = nil
	file_llama_proto_depIdxs = nil
}
